import { type AppType } from "next/app";
import { api } from "@/utils/api";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import "@/styles/globals.css";
import MainLayout from "../layouts/main-layout";
import Head from "next/head";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <UserProvider>
      <MainLayout>
        <Head>
          <title>BuildInWest</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </MainLayout>
    </UserProvider>
  );
};

export default api.withTRPC(MyApp);
