import { type AppType } from "next/app";
import { api } from "@/utils/api";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import "@/styles/globals.css";
import MainLayout from "../layouts/main-layout";
import Head from "next/head";
import { Provider } from "react-redux";
import store from "../store/redux-store";
import { Auth0Provider } from "@auth0/auth0-react";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <Auth0Provider
      clientId="CTvZyZqDcGsJGsobl9g1F3lTOOIgw46z"
      domain="https://dev-bd85cujrunisff2x.us.auth0.com"
    >
      <UserProvider>
        <Head>
          <title>BuildInWest</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Provider store={store}>
          <MainLayout>
            <Component {...pageProps} />
          </MainLayout>
        </Provider>
      </UserProvider>
    </Auth0Provider>
  );
};

export default api.withTRPC(MyApp);
