import { type AppType } from "next/app";
import { api } from "@/utils/api";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import "@/styles/globals.css";
import MainLayout from "../layouts/main-layout";
import Head from "next/head";
import { Provider } from "react-redux";
import store from "../store/redux-store";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <UserProvider>
      <Provider store={store}>
        <MainLayout>
          <Head>
            <title>BuildInWest</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </MainLayout>
      </Provider>
    </UserProvider>
  );
};

export default api.withTRPC(MyApp);
